- src/App.js
- src/pages/Login.jsx
- src/pages/index.js
> [FEAT][GROUP 28][LOGIN]

- package-lock.json
- package.json
- src/App.js
- src/components/Login.js
> [GRUPO 3][requisito-2-ao-8]

- package-lock.json
- src/pages/Login.js
- src/tests/Login.test.js
- src/tests/renderWithRouter.js
Adiciona todos os tests da page de Login
> [GRUPO-29] Adiciona todos os tests da page de Login

- package-lock.json
- src/App.js
- src/pages/Foods.jsx
- src/pages/Login.jsx
- src/pages/index.js
> [FEAT ][GROUP 28]: [Login]

- src/App.js
- src/components/HeaderSearchBar.js
- src/pages/Bebidas.js
- src/pages/BebidasDetails.js
- src/pages/Comidas.js
- src/pages/ComidasDetails.js
- src/services/SearchDrinksAPI.js
- src/services/SearchFoodsAPI.js
Foram adicionados os services SearchDrinksAPI e o  SearchFoodsAPI, que são utilizados no componente HeaderSearchBar.
As paginas Bebidas, BebidasDetails, Comidas, ComidasDetails são Placeholders e devem ser modificadas depois. 
No App.js foram colocadas as rotas para as paginas acima, que também são placeholders.
> [GRUPO 23] - Feitos requisitos 13 a 18 -17

- README.md
- src/App.js
- src/Components/Header/Header.css
- src/Components/Header/index.js
- src/Pages/MainDrink.js
- src/Pages/Profile.js
- src/Styles/Profile.css
O requisito 10 está parcialmente feito, porque ele testa se há um header em todas as páginas da aplicação, como não foram criadas ainda o teste não passa completamente.
> Requisitos 9, 10 e 11 - feitos

- src/components/Login.jsx
- src/services/localStorage.js
> Requisito 6 e 7

- package-lock.json
- src/App.css
- src/components/Login.js
> [GRUPO 3][fix-requisito-6-7]

- src/components/RecipeItemDrinks.jsx
- src/components/RecipesList.jsx
- src/pages/Explore.jsx
> Requisito 67, 68 e 69

- package-lock.json
- package.json
- src/App.jsx
- src/components/Header.jsx
- src/pages/Explore.jsx
- src/pages/ExploreDrinks.jsx
- src/pages/ExploreFoods.jsx
- src/pages/FavoriteRecipes.jsx
- src/pages/MainDrinks.jsx
- src/pages/MainFoods.jsx
- src/pages/Profile.jsx
- src/pages/RecipesMades.jsx
- src/pages/index.js
- src/styles/Header.css
> [Group-6] Feat - Header

- src/pages/ExploreDrink.jsx
- src/pages/ExploreFood.jsx
> Requisitos 70 a 73

- src/context/provider.js
- src/services/index.js
Implementa requisições à Api e faz o gerenciamento dos estados
> [FEAT][GROUP-28][Requisições de Api]

- src/App.css
- src/components/Footer.js
- src/pages/Bebidas.js
- src/pages/Comidas.js
- src/pages/Explorar.js
- src/pages/ExplorarBebidas.js
- src/pages/ExplorarBebidasIngredientes.js
- src/pages/ExplorarComidas.js
- src/pages/ExplorarComidasArea.js
- src/pages/ExplorarComidasIngredientes.js
- src/pages/Perfil.js
19 OK
20 OK
21 Depende dos anteriores
22 OK
23 OK
24 OK
> Requisito 21, depende dos anteriores

- package-lock.json
- src/components/Footer.jsx
- src/pages/Explore.js
- src/pages/ExploreDrinks.js
- src/pages/ExploreDrinksByIngredients.js
- src/pages/ExploreFoods.js
- src/pages/ExploreFoodsByIngredients.js
- src/pages/ExploreFoodsByLocal.js
- src/pages/Perfil.js
- src/pages/PrincipalDrinks.js
- src/pages/PrincipalFoods.js
- src/styles/footer.css
Requirements 19-24: adds the Footer component
> [MAIN GROUP 31] Footer

- src/App.js
- src/components/Footer/Footer.jsx
- src/components/Header/index.jsx
- src/pages/DrinkProgress/index.jsx
- src/pages/Drinks/index.jsx
- src/pages/Explore/index.jsx
- src/pages/ExploreDrinks/index.jsx
- src/pages/ExploreFood/index.jsx
- src/pages/ExploreFoodArea/index.jsx
- src/pages/Foods/index.jsx
- src/pages/Profile/index.jsx
- src/styles/GlobalStyles.jsx
> Main group 27 develop menu inferior req19 - oia só chefe

- src/App.js
- src/components/Profile.js
> [GRUPO 3][requisito-82-ao-87-feature]

- src/components/Header.jsx
- src/components/Recipes.jsx
- src/components/SearchBar.jsx
- src/styles/Header.css
- src/styles/Recipes.css
Também já foi mergeado todos as feats que o enio fez e o Pedro fez de css.
> [GROUP 26] - [Feats Css]

- cypress/integration/login_spec.js
- src/Pages/Login.js
- src/components/LoginForm.js
- src/tests/LoginForm.test.js
Foram inclusos, os inputs de: email, senha e o botão que submete os dados do formulário. Todos os elementos foram testados.
> feat: incluindo elementos na tela de login(tested)

- src/App.test.js
- src/pages/login.js
- src/tests/login.test.js
- src/tests/renderWithRouter.js
Alcançada cobertura de testes de 100% para a página de LOGIN - Cypress não validará o requisito 1 pois a cobertura de testes do projeto total ainda é 58%.
> Main group 15 requisito 2 increase test coverage

- src/components/SearchBar.jsx
- src/context/MealsAndDrinkProvider.js
- src/services/api.js
- src/tests/header.test.js
Removed the bug when no options are selected, applied the 'page' state on context to searchbar knows where it is rendered.
> refactor: changed and bug fix on searchbar component

- src/components/Header.jsx
- src/pages/Login.jsx
- src/tests/Header.test.js
- src/tests/Profile.test.js
- src/tests/helpers/renderWithRouter.js
> [Group-6] Tests

- src/App.js
- src/pages/Explore/index.jsx
- src/pages/ExploreDrinks/index.jsx
- src/pages/ExploreFood/index.jsx
- src/services/index.js
> Main group 27 develop tela de explorar req67

- src/App.js
- src/CSS/ProgressoBebidas.css
- src/components/CheckboxProgress.js
- src/context/mockInfo.js
- src/pages/ProgressoBebidas.js
- src/pages/ProgressoComidas.js
- src/pages/index.js
ProgressoBebidas.js e ProgressoComidas.js estao usando o msm arquivo de mock que vai ser alterado
> reqs 47, 48, 49, 52 e 53 mocados

- src/App.css
- src/components/DrinkCards.js
- src/components/MealCards.js
- src/index.js
- src/pages/Drinks.js
- src/pages/Foods.js
- src/redux/actions/index.js
- src/redux/reducers/drinkReducer.js
- src/redux/reducers/foodReducer.js
- src/redux/reducers/index.js
- src/services/index.js
> [FEAT] MealsCard/DrinkCard

- src/components/Header.js
- src/components/Login.js
- src/components/SearchBar.js
- src/context/Provider.js
- src/helpers/index.js
- src/pages/Drinks.js
- src/pages/Foods.js
- src/services/api.js
> [Main group 33][barra de buscas header]

- src/App.js
- src/components/Header.js
- src/pages/Explore.js
- src/pages/Main.js
- src/pages/Profile.js
- src/pages/RecipeDetails.js
- src/pages/RecipeList.js
- src/pages/RecipeProgress.js
- src/routes/index.js
- src/services/pageTitles.js
1. Cria os seguintes componentes básicos (com as exigências dos testes, sem suas lógicas completas de renderização) em `src/pages`:
- `Main`;
- `RecipeList`;
- `RecipeProgress`;
- `RecipeDetails`;
- `Explore`;
- `Profile`.
2. Cria, em `routes/index`, as rotas para os componentes listados no item 1;
3. Cria, em `services/pageTitle`, módulo para lidar com as lógicas dos títulos das páginas de acordo com o _path_ acessado pela pessoa usuária;
4. Implementa as lógicas do componente `components/Main` referentes aos requisitos [9](https://github.com/tryber/sd-09-project-recipes-app#9---implemente-os-elementos-do-header-na-tela-principal-de-receitas-respeitando-os-atributos-descritos-no-prot%C3%B3tipo) e [10](https://github.com/tryber/sd-09-project-recipes-app#10---implemente-um-%C3%ADcone-para-a …
> [Grupo 2] feat(Header): Adiciona requisitos 9 e 10

- src/pages/Login.js
Coloca tipos (email e password) nos inputs de login
> [FIX][Login][Adiciona tipos nos inputs]

- src/components/SearchBar.jsx
- src/context/provider.js
- src/services/index.js
> [FEAT][GROUP 28][SearchBar] 

- src/pages/exploreScreen/index.js
- src/pages/exploreScreen/styles.css
Implementa a tela de Explorar, com os botões que direcionam para as telas de comidas e bebidas.
> Main Group 7 - Requisitos 67, 68 e 69

- src/components/AllRoutes.jsx
- src/pages/ExploreMealByOrigin.jsx
- src/pages/NotFound.jsx
- src/services/APIEndpoints.js
> [Grupo 9][ Meals by area page]

- src/actions/index.js
- src/components/searchBar.js
- src/reducers/recipesReducer.js
Implementada a renderizaçao dos resultados de pesquisa e  redirecionamento para pagina de detalhes quando resultado for so uma receita
> Requisitos 16 e 17

- src/pages/profile.js
- src/services/servicesLocalStorage.js
> Patch na funçao de coletar dados do localStorage

- src/components/MainCards.jsx
- src/components/SearchBar.jsx
- src/pages/Drinks.jsx
- src/pages/Foods.jsx
> [FEAT][GROUP28][SEARCHBAR]

- src/components/Explorer.js
- src/pages/DetalheComidas.js
- src/pages/Explorar.js
- src/pages/ExplorarBebidas.js
- src/pages/ExplorarComidas.js
> Main group 34 req 70

- src/App.js
- src/components/Footer.jsx
- src/context/MealContext.jsx
- src/context/MealProvider.jsx
- src/pages/DetalhesBebida.jsx
- src/pages/DetalhesComida.jsx
- src/pages/ExplorarComidasArea.jsx
- src/pages/ExplorarComidasIng.jsx
- src/pages/PrincipalBebidas.jsx
- src/pages/PrincipalComidas.jsx
- src/pages/ProcessoBebida.jsx
- src/pages/ProcessoComida.jsx
- src/pages/ReceitasFavoritas.jsx
- src/pages/ReceitasFeitas.jsx
- src/pages/TelaDePerfil.jsx
- src/services/MealFetch.jsx
- src/styles/recipes.css
Requisição para a API não está funcionando :(
> [Group 14] [footer, explorer e profile]

- src/pages/Profile.js
> [FEAT][Requisito 82 ao 87][tela de perfil][V1.0]

- cypress/integration/recipe_detail_spec.js
- src/components/StartRecipeButton.js
- src/context/Provider.js
- src/services/inProgressRecipes.js
Botão de Iniciar/Continuar Receita
> [FEAT][Requisito 40][Implementa solução de continuar receita]

- src/components/ListIngredientsCards/index.jsx
- src/components/ListIngredientsCards/styled.jsx
- src/context/index.jsx
- src/hooks/useFoodApi.js
- src/pages/Drinks/index.jsx
- src/pages/ExploreDrinksIngredients/index.jsx
- src/pages/ExploreFoodIngredients/index.jsx
- src/pages/Foods/index.jsx
> Main group 27 develop expl ingredients leo - req 75 - 76 -77

- package-lock.json
- package.json
- src/components/RecomendationCard.js
- src/pages/RecipeDetails.js
Implemente os cards de recomendação, onde serão 6 cards, mas mostrando apenas 2 e o scroll é horizontal, similar a um carousel
> [FEAT][Requisito 37][Implemente os cards de recomendação]

- .stylelintignore
- cypress/integration/done_recipes_spec.js
- cypress/integration/explore_by_area_spec.js
- cypress/integration/explore_by_ingredient_spec.js
- cypress/integration/explore_drinks_or_meals_spec.js
- cypress/integration/explore_spec.js
- cypress/integration/favorite_recipes_spec.js
- cypress/integration/footer_spec.js
- cypress/integration/login_spec.js
- cypress/integration/profile_spec.js
- cypress/integration/recipe_in_progress_spec.js
- package.json
- src/App.css
- src/components/DrinkCards.js
- src/components/Header.js
- src/components/MealCards.js
- src/components/SearchBar.js
- src/pages/Foods.js
Resolvendo conflitos e problemas com a estilização.
> [FIX] CSS e Requistos

- src/App.css
- src/components/MainCards.jsx
- src/components/SearchBar.jsx
- src/components/buttons/explore/ExploreDrinksButton.jsx
- src/components/buttons/explore/ExploreDrinksIngredientsBtn.jsx
- src/components/buttons/explore/ExploreFoodsAreaBtn.jsx
- src/components/buttons/explore/ExploreFoodsButton.jsx
- src/components/buttons/explore/ExploreFoodsIngredientsBtn.jsx
- src/components/buttons/explore/SurpriseMeBtn.jsx
- src/components/buttons/profile/DoneRecipesButton.jsx
- src/components/buttons/profile/FavoriteRecipesButton.jsx
- src/components/buttons/profile/LogoutButton.jsx
- src/pages/Drinks.jsx
- src/pages/Explore.jsx
- src/pages/ExploreDrinks.jsx
- src/pages/ExploreFoods.jsx
- src/pages/Foods.jsx
- src/pages/Login.jsx
- src/pages/Profile.jsx
Estilização primaria das paginas, botoes e cards
> [FEAT][GROUP-28][CSS]

- src/components/ShareButton/ShareButton.css
- src/components/ShareButton/index.js
- src/context/Provider.js
Implementa botão de compartilhar URL
> Group 18 share button

- src/pages/ExplorerDrink.js
- src/pages/ExplorerFood.js
- src/services/RecipesApi.js
> [FEAT] [Requisito 74] [implementando o "me surpreenda!"] v1.0

- cypress/integration/recipe_in_progress_spec.js
- src/components/Details/TitleContainer.jsx
- src/components/ListFavoriteCards/index.jsx
- src/context/index.jsx
- src/pages/DoneRecipes/index.jsx
- src/pages/DrinkProgress/index.jsx
- src/pages/FavoriteRecipes/index.jsx
- src/pages/FoodProgress/index.jsx
- src/services/localStorage.js
Reverts tryber/sd-09-project-recipes-app#630
> [ Main group 27 ] - [TELA DE RECEITAS EM PROGRESSO]

- src/App.css
- src/App.js
- src/pages/DrinksByIngredients.js
- src/pages/Explore.js
- src/pages/ExploreDrinks.js
- src/pages/ExploreFoods.js
- src/pages/FoodsByArea.js
- src/pages/FoodsByIngredients.js
- src/services/index.js
> [FEAT] ExploreFoods/ExploreDrinks

- src/App.css
- src/pages/DrinkDetails.jsx
- src/pages/FoodDetails.jsx
Implementação da tela de detalhes de comidas e bebidas
> [Feat][GRUOP 28]:[tela de detalhes]

- src/App.css
- src/components/MainCards.jsx
- src/components/buttons/categories/CategoriesBtn.jsx
realizado requisito 32 e corrigido issues do eslint
> [FEAT][GROUP 28][TELA PRINCIPAL]

- src/App.css
> [FIX][GROUP 28][TELA PRINCIPAL]

- src/pages/exploreScreen/index.js
- src/pages/exploreScreen/styles.css
- src/pages/profile/index.js
- src/pages/profile/styles.css
- src/reducer/exploreData.js
- src/reducer/recipeData.js
> Profile Screen

- src/components/Ingredients/Index.js
Implementa função de redirecionamento à página principal caso algum ingrediente seja clicado, exibindo apenas receitas deste ingrediente.
> [FEAT][Requisito 77][Redireciona usuário ao clicar em um ingrediente]

- src/components/CardRecipe/index.js
Redirecione para a tela de detalhes da receita caso seja clicado na foto ou no nome da receita
> [FEAT][Requisito 59][Redirecione para a tela de detalhes da receita]

- src/App.css
- src/components/buttons/categories/CategoriesBtn.jsx
> [FIX][GROUP 28][CSS]

- src/App.js
- src/pages/Explore.jsx
- src/pages/ExploreDrinks.jsx
- src/pages/ExploreMeals.jsx
> feat: added requirements 67 up to 69 explore screen

- src/App.js
- src/pages/ExploreDrinks.jsx
- src/pages/ExploreIngredients.jsx
- src/pages/ExploreMeals.jsx
- src/pages/ExploreOrigin.jsx
> feat: added requirements 70-74 exploredrinksandmeals screens

- package.json
- src/App.css
- src/App.js
- src/components/IngredientFilter.js
- src/components/MealVideo.js
- src/components/detailHeader.js
- src/components/ingredientCheckbox.js
- src/components/ingredientList.js
- src/components/startEndButton.js
- src/pages/foodInProcess.js
- src/pages/recipeDetails.js
- src/pages/recipeInProcess.js
Conclusão da página de detalhes
> Requisitos 39 ao 46

- src/components/buttons/categories/CategoriesBtn.jsx
- src/components/buttons/explore/ExploreFoodsAreaBtn.jsx
- src/components/buttons/explore/ExploreFoodsIngredientsBtn.jsx
- src/components/buttons/explore/SurpriseMeBtn.jsx
- src/context/provider.js
- src/services/index.js
> [FEAT][GROUP 28][TELA DE EXPLORAR]

- src/context/provider.js
- src/pages/ExploreDrinksIngredients.jsx
- src/pages/ExploreFoodsIngredients.jsx
- src/services/index.js
> [FEAT][GROUP 28][TELA EXPLORAR POR INGREDIENTE]

- src/pages/DrinkIngredients.js
- src/pages/FoodIngredients.js
- src/services/RecipesApi.js
> [FEAT] [requisitos 75 e 76] v1.0 

- src/context/provider.js
> [FIX][GROUP 28][TELA EXPLORAR POR INGREDIENTE]

- src/components/Providers/LoginProvider.jsx
- src/components/Providers/RecipesProvider.jsx
- src/components/Router.jsx
- src/components/ShareButton.jsx
- src/pages/EmProcesso.jsx
- src/services/cocktailsAPI.js
- src/styles/InProgress.css
> [GRUPO 01] [TELA DE RECEITAS EM PROGRESSO]

- src/context/provider.js
- src/pages/FoodDetails.jsx
- src/pages/Profile.jsx
Arrumando os requisitos 82 e 83
> [GROUP 28][Fix]requisito 82 83

- src/pages/DrinkDetails.jsx
Ajusta o segundo tópico do requisito 46, salvando corretamente se a bebida é ou não alcoólica.
> [FIX][GROUP 28][TELA DE DETALHES]

- src/App.js
- src/Pages/Explorar/DrinksDetails.js
- src/Pages/Explorar/ExploreDrinks.js
- src/Pages/Explorar/ExploreFoods.js
- src/Pages/Explorar/FoodDetails.js
- src/Pages/Explorar/IngredientsDrinks.js
- src/Pages/Explorar/IngredientsFoods.js
- src/components/Loading.js
- src/services/randomDrink.js
- src/services/randomFood.js
> Main group 20 botao me surpreenda

- src/components/RecipesCards.jsx
- src/pages/FavoriteRecipes.jsx
> [FEAT][GROUP 28][TELA DE RECEITAS FAVORITAS]

- src/components/CopyMsg.js
- src/components/RecipeListCard.js
- src/components/ShareButton.js
- src/pages/RecipeList.js
- src/services/api.js
- src/services/getPath.js
- Adiciona `components/CopyMsg`:
> Componente exibe mensagem "Link copiado!" em
> document.root independentemente de onde é chamado.
- Adiciona `components/ShareButton`:
> - Agora é uma div clicável com imagem children;
> - Serve em qualquer página com props adequadas;
> - Copia URL sem bibliotecas externas.
- `components/RecipeListCard`:
> Refatorada para uso de `ShareButton` & `CopyMsg`.
- `pages/RecipeList`:
> Refatorada para uso de `ShareButton` & `CopyMsg`.
- `services/getPath`:
> - Função `getRecipeDetailsPath` retorna path da
>   página de detalhes da receita;
> - Serve em qualquer página com props adequadas.
> [Grupo 2] (fix/refac) Corrige requisitos 57 e 63 e refatora componentes

- src/components/RecipesCards.jsx
> [FET][GROUP 28][TELA-DE-RECEITAS-FAVORITAS]

- src/components/RecipeDetailsHeader.jsx
- src/components/RecipeFavoriteButton.jsx
- src/components/RecipeIngredients.jsx
- src/components/RecipeIngredientsList.jsx
- src/components/RecipeInstructions.jsx
- src/components/RecipeShareButton.jsx
- src/components/RecipeStartButton.jsx
- src/pages/DrinkDetails.jsx
- src/pages/DrinkInProgress.jsx
- src/pages/RecipeDetails.jsx
- src/pages/RecipeInProgress.jsx
- src/styles/components/RecipeIngredients.css
> [Group-6][Feat] - Recipes in Progress

- src/pages/DoneRecipes.jsx
- src/pages/DrinkInProgress.jsx
- src/pages/FavoriteRecipes.jsx
- src/pages/RecipeInProgress.jsx
- src/styles/FavoriteRecipes.css
- src/styles/pages/DoneRecipes.css
- src/styles/pages/InProgress.css
> [Group-6][Feat] - Done Recipes

- src/components/MainCards.jsx
- src/components/RecipesCards.jsx
- src/components/RecipesList.jsx
- src/pages/DrinkDetails.jsx
- src/pages/DrinkInProgress.jsx
- src/pages/ExploreDrinksIngredients.jsx
- src/pages/ExploreFoodsArea.jsx
- src/pages/ExploreFoodsIngredients.jsx
- src/pages/FoodDetails.jsx
- src/pages/FoodInProgress.jsx
- src/pages/Login.jsx
> [FEAT][GROUP 28][EXPLORE BY AREA]

- src/App.css
- src/components/IngredientFilter.js
- src/components/detailHeader.js
- src/components/finnishARecipe.js
- src/components/ingredientCheckbox.js
- src/components/ingredientList.js
- src/pages/doneAndFavoriteRecipes.js
- src/pages/recipeInProcess.js
Concluída a pagina de receitas em progresso.
> Main group 15 recipes in progress
